# Generated by Django 3.0.7 on 2020-06-30 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='clave',
            field=models.SlugField(max_length=100, unique=True, verbose_name='Nombre clave'),
        ),
    ]
