# Generated by Django 3.0.7 on 2020-07-01 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0002_auto_20200630_1605'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='link',
            options={'ordering': ['nombre'], 'verbose_name': 'enlace', 'verbose_name_plural': 'enlaces'},
        ),
    ]
