# Generated by Django 3.0.7 on 2020-07-01 22:56

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20200701_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pages',
            name='contenido',
            field=ckeditor.fields.RichTextField(verbose_name='Contenido'),
        ),
    ]
